### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by dvershinin** [weserv/rate-limit-nginx-module#2]
Since it is production-ready, can you please tag a release version [here](https://github.com/weserv/rate-limit-nginx-module/releases), e.g. 1.0.0?

**Comment by kleisauke** [comment]
Hi @dvershinin,

I'm a bit reluctant to tag a release version because the Redis module where this Nginx module depends on has a bug that causes the rate limiter to misbehave on short periods. See:
https://github.com/weserv/rate-limit-nginx-module/issues/1#issuecomment-506328650
https://github.com/onsigntv/redis-rate-limiter/pull/4

I'll tag a release version once the above pull request is merged (our production servers already run on this PR, fwiw).

**Comment by kleisauke** [comment]
The above mentioned PR was merged, so I just tagged [v1.0.0](https://github.com/weserv/rate-limit-nginx-module/releases/tag/v1.0.0).

FWIW, these `.spec` files might be interesting, if you plan to distribute this as an RPM package:
https://github.com/weserv/rpms/blob/4fd64cd8e205eb143a048fc6fd32b44553265c74/nginx-mod-rate-limit/nginx-mod-rate-limit.spec
https://github.com/weserv/rpms/blob/4fd64cd8e205eb143a048fc6fd32b44553265c74/redis-rate-limiter/redis-rate-limiter.spec
