### ISSUE TITLE
cluster sync

### ISSUE THREAD

**Issue by nikola-g-kovacevic** [weserv/rate-limit-nginx-module#3]
Is there a way to use this to sync rate limits on multiple load balancer servers in cluster?

**Comment by kleisauke** [comment]
Although I have never tried this in combination with [onsigntv/redis-rate-limiter](https://github.com/onsigntv/redis-rate-limiter), I think you could use Redis Cluster for this (a built-in Redis feature). 

Note that if you test with PR https://github.com/onsigntv/redis-rate-limiter/pull/4, be sure to build with the real-time clock (default) rather than the monotonic clock to ensure that the correct rate limits are synchronized in the cluster.

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
