### ISSUE TITLE
TIME_WAIT

### ISSUE THREAD

**Issue by bnchdan** [weserv/rate-limit-nginx-module#5]
The connections with redis will remain in TIME_WAIT state for a period of time (I think 1 - 4 minute). If you log  10.000 / minute you will have aprox 10.000 connection in time_wait state.

**Comment by kleisauke** [comment]
Have you tuned the `sysctl` settings on your server? Are you using:
```nginx
server 127.0.0.1:6379;
```
(i.e. Redis listening on the loopback interface)

Or:
```nginx
server unix:/var/run/redis/redis.sock;
```
(i.e. Redis listening on a Unix socket)

AFAIK, this shouldn't happen, unless you changed `net.ipv4.tcp_tw_reuse`, or using the former configuration, see:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=79e9fed460385a3d8ba0b5782e9e74405cb199b1

**Comment by bnchdan** [comment]
I have net.ipv4.tcp_tw_reuse set to 1. 

In my opinion is normal connection to remain in TIME_WAIT.  

I think the socket willl be reuse when will no be available sockets (I think ~28.000) or pass a limit.

The client should not be bind programmatically set to a default port (or a range of default ports) and if is not available or in state TIME_WAIT select a random port? Do you think this will not be a better approach?

Can you take a look at this example https://github.com/bnchdan/c2redis ?

**Comment by kleisauke** [comment]
AFAIK, you can't control the `TIME_WAIT` duration, it is hardcoded at 60s. Some people also recommend setting the `net.ipv4.tcp_tw_recycle` option, despite its removal from Linux in 4.12, see:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4396e46187ca5070219b81773c4e65088dac50cc

Your question about using random ports doesn't seem to make much sense to me, but maybe I'm misunderstanding.

This isn't really a question about this nginx module. If you need further help, perhaps try a more general site such as StackOverflow for this sort of question. Good luck!

**Comment by bnchdan** [comment]
I know that you can not control the TIME_WAIT duration .

My suggestion is if you have 10 connections/ minute is to reuse the same socket/sockets (if possible ) in state 'TIME_WAIT', not to have 10 connection in state 'TIME_WAIT'.

**Comment by andrieslouw** [comment]
If you're experiencing problems with the TCP overhead, the answer is using unix sockets. We haven't implemented connection pooling, and would not really recommend to do this inside nginx modules (I'm afraid that without a lot of care, you will run into issues due to the way nginx uses threads and processes).

There is another solution if you really want fast TCP sockets to redis with less overhead: Proxying redis. For example, take a look at https://github.com/twitter/twemproxy it will allow you to use unix sockets at the local server, and pool the TCP connections to your redis instance. This has the additional benefit of pooling connections and requests from different applications on that server.

But as said, this is more into redis advice, and less into the work on the nginx rate limiting module.
